#include <ql/qldefines.hpp>
#include <ql/version.hpp>
#include <ql/errors.hpp>
#include <ql/mathconstants.hpp>
#include <ql/settings.hpp>
#include <ql/types.hpp>
#include <ql/patterns/all.hpp>
#include <ql/time/all.hpp>
#include <ql/utilities/all.hpp>
