# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

advanceDemo <- function(rd) {
    invisible(.Call('RcppQuantuccia_advanceDemo', PACKAGE = 'RcppQuantuccia', rd))
}

advanceDate <- function(rd, days = 0L) {
    .Call('RcppQuantuccia_advanceDate', PACKAGE = 'RcppQuantuccia', rd, days)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RcppQuantuccia_RcppExport_registerCCallable', PACKAGE = 'RcppQuantuccia')
})
